import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({
  accelerateUrl: process.env.POSTGRES_PRISMA_URL,
});

const groups = [
  // ===================== SOUTHWARK =====================
  {
    externalId: "exp-football-southwark-1",
    sport: "Football",
    borough: "Southwark",
    name: "London City Athletics Club",
    venue: "Southwark Park Athletics Track",
    area: "Bermondsey",
    level: "All levels",
    description: "Athletics and football club based in Southwark, offering track sessions and community sports programmes across the borough.",
    contact: "https://www.londoncityac.com",
    sourceUrl: "https://www.londoncityac.com",
    isVenue: false,
  },
  {
    externalId: "exp-running-southwark-1",
    sport: "Running",
    borough: "Southwark",
    name: "London City Runners",
    venue: "Bermondsey & Southwark area",
    area: "Bermondsey",
    level: "All levels",
    description: "Community running club based in Bermondsey, central Southwark. Regular group runs for all abilities through local parks and along the Thames.",
    contact: "https://www.londoncityrunners.com",
    sourceUrl: "https://www.londoncityrunners.com",
    isVenue: false,
  },
  {
    externalId: "exp-running-southwark-2",
    sport: "Running",
    borough: "Southwark",
    name: "Dulwich Runners AC",
    venue: "Dulwich Park & Crystal Palace",
    area: "Dulwich",
    level: "All levels",
    description: "Established athletics club based in Dulwich with over 400 members. Offers road running, cross-country, track and field, and social running for all abilities.",
    contact: "https://www.dulwichrunners.org.uk",
    sourceUrl: "https://www.dulwichrunners.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-southwark-3",
    sport: "Running",
    borough: "Southwark",
    name: "Dulwich Park Runners",
    venue: "Dulwich Park",
    area: "Dulwich",
    level: "All levels",
    description: "Friendly community running club based in Dulwich Park. Weekly group runs and social events for runners of all levels.",
    contact: "https://www.dulwichparkrunners.co.uk",
    sourceUrl: "https://www.dulwichparkrunners.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-basketball-southwark-1",
    sport: "Basketball",
    borough: "Southwark",
    name: "London Thunder Basketball Club",
    venue: "Lewisham & Southwark venues",
    area: "Peckham",
    level: "All levels",
    description: "Sports charity based between Lewisham and Southwark offering basketball coaching and competitive play for young people and adults in the community.",
    contact: "https://www.neighbourly.com/project/63244146a816e7369377c8b3",
    sourceUrl: "https://www.neighbourly.com/project/63244146a816e7369377c8b3",
    isVenue: false,
  },

  // ===================== WANDSWORTH =====================
  {
    externalId: "exp-running-wandsworth-1",
    sport: "Running",
    borough: "Wandsworth",
    name: "Wandsworth Run Club",
    venue: "Sambrooks Brewery, Bellwether Lane",
    area: "Wandsworth",
    level: "All levels",
    description: "Community running club founded in June 2024. Weekly social runs from Sambrooks Brewery in Wandsworth, welcoming runners of all abilities.",
    contact: "https://www.wandsworthrunningclub.com",
    sourceUrl: "https://www.wandsworthrunningclub.com",
    isVenue: false,
  },
  {
    externalId: "exp-running-wandsworth-2",
    sport: "Running",
    borough: "Wandsworth",
    name: "Tooting Run Club",
    venue: "Tooting Bec Athletics Track & Tooting Common",
    area: "Tooting",
    level: "All levels",
    description: "Free community run club based in Tooting, Wandsworth. Train at Tooting Bec Athletics Track and on Tooting Common. Registered charity (1213800).",
    contact: "https://www.tootingrunclub.com",
    sourceUrl: "https://www.tootingrunclub.com",
    isVenue: false,
  },
  {
    externalId: "exp-running-wandsworth-3",
    sport: "Running",
    borough: "Wandsworth",
    name: "Clapham Chasers",
    venue: "Clapham Common",
    area: "Clapham",
    level: "All levels",
    description: "Popular community running club based on Clapham Common. Multiple weekly sessions including interval training, tempo runs and social runs for all abilities.",
    contact: "https://www.claphamchasers.co.uk",
    sourceUrl: "https://www.claphamchasers.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-padel-wandsworth-1",
    sport: "Padel",
    borough: "Wandsworth",
    name: "Playtime Padel Club Tooting",
    venue: "Tooting & Battersea venues",
    area: "Tooting",
    level: "All levels",
    description: "Local padel club with courts in Tooting, Barnes and Battersea. Pay and play available with social sessions, private coaching and match play.",
    contact: "https://www.playtimepadelclub.com",
    sourceUrl: "https://www.playtimepadelclub.com",
    isVenue: true,
  },
  {
    externalId: "exp-tennis-wandsworth-1",
    sport: "Tennis",
    borough: "Wandsworth",
    name: "All Star Tennis Wandsworth",
    venue: "King George's Park & Battersea Park",
    area: "Wandsworth",
    level: "All levels",
    description: "Community tennis programme across Wandsworth parks including King George's Park and Battersea Park. Coaching for all ages and abilities, social tennis and cardio sessions.",
    contact: "https://www.allstartennis.co.uk",
    sourceUrl: "https://www.allstartennis.co.uk",
    isVenue: true,
  },
  {
    externalId: "exp-football-wandsworth-1",
    sport: "Football",
    borough: "Wandsworth",
    name: "Terrible Football London",
    venue: "Various Wandsworth & South London parks",
    area: "Wandsworth",
    level: "Beginner",
    description: "Casual, fun football in London parks for people who want to play but aren't ready for competitive leagues. No pressure, no commitment, just fun kickabouts.",
    contact: "https://www.meetup.com/terrible-football-in-london/",
    sourceUrl: "https://www.meetup.com/terrible-football-in-london/",
    isVenue: false,
  },

  // ===================== LEWISHAM =====================
  {
    externalId: "exp-football-lewisham-1",
    sport: "Football",
    borough: "Lewisham",
    name: "AFC Lewisham",
    venue: "Ladywell Arena & local pitches",
    area: "Lewisham",
    level: "All levels",
    description: "Community football club based in Lewisham offering youth and adult football. Multiple age groups competing in local leagues.",
    contact: "https://www.afclewisham.com",
    sourceUrl: "https://www.afclewisham.com",
    isVenue: false,
  },
  {
    externalId: "exp-football-lewisham-2",
    sport: "Football",
    borough: "Lewisham",
    name: "Lewisham Borough Community FC",
    venue: "Ladywell Arena",
    area: "Catford",
    level: "All levels",
    description: "Community football club accessible to Lewisham residents, supported by local businesses. Competes in the SCEFL and runs community programmes.",
    contact: "https://www.scefl.com/sceflclub-lewisham",
    sourceUrl: "https://www.scefl.com/sceflclub-lewisham",
    isVenue: false,
  },
  {
    externalId: "exp-running-lewisham-1",
    sport: "Running",
    borough: "Lewisham",
    name: "Kent AC",
    venue: "Ladywell Arena",
    area: "Lewisham",
    level: "All levels",
    description: "Historic athletics club based at Ladywell Arena in Lewisham. One of the oldest running clubs in the country with road running, cross-country and track & field.",
    contact: "https://www.kentac.org.uk",
    sourceUrl: "https://www.runnersguidetolondon.co.uk/london-running-clubs.html",
    isVenue: false,
  },
  {
    externalId: "exp-basketball-lewisham-1",
    sport: "Basketball",
    borough: "Lewisham",
    name: "London Thunder Basketball Club",
    venue: "Lewisham venues",
    area: "Lewisham",
    level: "All levels",
    description: "Sports charity running basketball coaching and competitive play for young people and adults in Lewisham and Southwark communities.",
    contact: "https://www.neighbourly.com/project/63244146a816e7369377c8b3",
    sourceUrl: "https://www.neighbourly.com/project/63244146a816e7369377c8b3",
    isVenue: false,
  },

  // ===================== GREENWICH =====================
  {
    externalId: "exp-running-greenwich-1",
    sport: "Running",
    borough: "Greenwich",
    name: "Cambridge Harriers",
    venue: "Sutcliffe Park Athletics Track",
    area: "Eltham",
    level: "All levels",
    description: "Athletics club based in Eltham, Greenwich offering road running, cross-country, track and field for juniors and seniors.",
    contact: "https://www.cambridgeharriers.org.uk",
    sourceUrl: "https://www.cambridgeharriers.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-greenwich-2",
    sport: "Running",
    borough: "Greenwich",
    name: "Greenwich Tritons Triathlon Club",
    venue: "Greenwich & Eltham venues",
    area: "Greenwich",
    level: "All levels",
    description: "Triathlon club based in Greenwich offering swimming, cycling and running training sessions. Caters for beginners to experienced triathletes.",
    contact: "https://www.greenwichtritons.org.uk",
    sourceUrl: "https://www.greenwichtritons.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-cycling-greenwich-1",
    sport: "Cycling",
    borough: "Greenwich",
    name: "Woolwich Cycling Club",
    venue: "Various routes from Greenwich/Bexley",
    area: "Woolwich",
    level: "All levels",
    description: "Community cycling club based in the Woolwich and Greenwich area. Regular weekend rides and social cycling for all abilities.",
    contact: "https://www.woolwichcyclingclub.org.uk",
    sourceUrl: "https://www.woolwichcyclingclub.org.uk",
    isVenue: false,
  },

  // ===================== NEWHAM =====================
  {
    externalId: "exp-running-newham-1",
    sport: "Running",
    borough: "Newham",
    name: "East End Road Runners",
    venue: "Newham Leisure Centre & local parks",
    area: "Newham",
    level: "All levels",
    description: "Friendly, all-level community running club based in Newham, East London. Regular training sessions for beginners through to experienced road runners.",
    contact: "https://www.eerr.org.uk",
    sourceUrl: "https://www.eerr.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-newham-2",
    sport: "Running",
    borough: "Newham",
    name: "Newham & Essex Beagles AC",
    venue: "Newham Leisure Centre",
    area: "Plaistow",
    level: "All levels",
    description: "Athletics club based in Plaistow, Newham. Track and field, road running and cross-country for juniors and seniors.",
    contact: "https://www.newhamandessexbeagles.co.uk",
    sourceUrl: "https://www.newhamandessexbeagles.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-football-newham-1",
    sport: "Football",
    borough: "Newham",
    name: "West Ham United Foundation",
    venue: "London Stadium & community venues",
    area: "Stratford",
    level: "All levels",
    description: "Community arm of West Ham United FC running football programmes, coaching sessions and community engagement across Newham and East London.",
    contact: "https://www.whufc.com/club/foundation",
    sourceUrl: "https://www.whufc.com/club/foundation",
    isVenue: false,
  },

  // ===================== BARNET =====================
  {
    externalId: "exp-running-barnet-1",
    sport: "Running",
    borough: "Barnet",
    name: "Barnet & District AC",
    venue: "Oakhill Park & Southgate area",
    area: "Southgate",
    level: "All levels",
    description: "Athletics club based in Southgate covering road running, cross-country and track events. Active in local leagues and competitions.",
    contact: "https://www.barnetadac.com",
    sourceUrl: "https://www.barnetadac.com",
    isVenue: false,
  },
  {
    externalId: "exp-running-barnet-2",
    sport: "Running",
    borough: "Barnet",
    name: "Shaftesbury Barnet Harriers",
    venue: "Copthall Stadium, Hendon",
    area: "Hendon",
    level: "All levels",
    description: "Major athletics club based at Copthall Stadium in Hendon. Track and field, road running and cross-country for all ages. One of London's largest athletic clubs.",
    contact: "https://www.shaftesburybarnet.co.uk",
    sourceUrl: "https://www.shaftesburybarnet.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-football-barnet-1",
    sport: "Football",
    borough: "Barnet",
    name: "Barnet FC Community Trust",
    venue: "The Hive London, Edgware",
    area: "Edgware",
    level: "All levels",
    description: "Community trust of Barnet FC running football coaching, walking football, disability football and community engagement across the borough.",
    contact: "https://www.barnetfc.com/community",
    sourceUrl: "https://www.barnetfc.com/community",
    isVenue: false,
  },

  // ===================== EALING =====================
  {
    externalId: "exp-running-ealing-1",
    sport: "Running",
    borough: "Ealing",
    name: "Ealing Eagles Running Club",
    venue: "Lammas Park, Ealing",
    area: "Ealing",
    level: "All levels",
    description: "West London running club with over 700 members from complete beginners to seasoned marathon runners. Multiple weekly sessions from Lammas Park.",
    contact: "https://www.ealingeagles.com",
    sourceUrl: "https://www.ealingeagles.com",
    isVenue: false,
  },
  {
    externalId: "exp-running-ealing-2",
    sport: "Running",
    borough: "Ealing",
    name: "Ealing Southall & Middlesex AC",
    venue: "Perivale Park Athletics Track",
    area: "Greenford",
    level: "All levels",
    description: "West London athletics club of 400+ members aged 9-69, from beginners to internationals. Track and field, road and cross-country running.",
    contact: "https://www.esm.org.uk",
    sourceUrl: "https://www.esm.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-football-ealing-1",
    sport: "Football",
    borough: "Ealing",
    name: "5 a side football in Ealing",
    venue: "Lammas Park, Ealing",
    area: "Ealing",
    level: "All levels",
    description: "Weekly casual 5-a-side football game in Ealing at Lammas Park. All levels welcome, friendly atmosphere. Organised via Meetup.",
    contact: "https://www.meetup.com/topics/5-a-side/gb/",
    sourceUrl: "https://www.meetup.com/topics/5-a-side/gb/",
    isVenue: false,
  },

  // ===================== BRENT =====================
  {
    externalId: "exp-running-brent-1",
    sport: "Running",
    borough: "Brent",
    name: "Queen's Park Harriers",
    venue: "Willesden Sports Centre",
    area: "Willesden",
    level: "All levels",
    description: "Athletics club based in Willesden, Brent. Road running, cross-country and track sessions for all abilities.",
    contact: "https://www.queensparkharriers.org.uk",
    sourceUrl: "https://www.queensparkharriers.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-brent-2",
    sport: "Running",
    borough: "Brent",
    name: "Sudbury Court Running Club",
    venue: "Wembley area",
    area: "Wembley",
    level: "All levels",
    description: "Friendly community running club based in Wembley. Regular weekly runs and training sessions for runners of all abilities.",
    contact: "https://www.sudburycourt.org.uk",
    sourceUrl: "https://www.sudburycourt.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-football-brent-1",
    sport: "Football",
    borough: "Brent",
    name: "Wembley FC",
    venue: "Vale Farm Sports Centre",
    area: "Wembley",
    level: "All levels",
    description: "Historic community football club based at Vale Farm in Wembley. One of the oldest amateur clubs in London with senior and youth teams.",
    contact: "https://www.wembleyfc.co.uk",
    sourceUrl: "https://www.wembleyfc.co.uk",
    isVenue: false,
  },

  // ===================== ENFIELD =====================
  {
    externalId: "exp-running-enfield-1",
    sport: "Running",
    borough: "Enfield",
    name: "Enfield and Haringey AC",
    venue: "QE II Stadium, Edmonton",
    area: "Edmonton",
    level: "All levels",
    description: "Athletics club based at the QE II Stadium. Track and field, road running and cross-country for juniors and seniors across Enfield and Haringey.",
    contact: "https://www.ehac.co.uk",
    sourceUrl: "https://www.ehac.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-enfield-2",
    sport: "Running",
    borough: "Enfield",
    name: "Edmonton Running Club",
    venue: "Winchmore Hill area",
    area: "Winchmore Hill",
    level: "All levels",
    description: "Community running club based in Winchmore Hill, Enfield. Weekly group runs and training sessions for all levels.",
    contact: "https://www.edmontonrc.co.uk",
    sourceUrl: "https://www.edmontonrc.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-enfield-3",
    sport: "Running",
    borough: "Enfield",
    name: "Trent Park Running Club",
    venue: "Trent Park, Oakwood",
    area: "Oakwood",
    level: "All levels",
    description: "Community running club based in Trent Country Park, Oakwood. Trail and road running through the beautiful parkland of North London.",
    contact: "https://www.trentparkrc.org",
    sourceUrl: "https://www.trentparkrc.org",
    isVenue: false,
  },
  {
    externalId: "exp-football-enfield-1",
    sport: "Football",
    borough: "Enfield",
    name: "Enfield Town FC",
    venue: "Queen Elizabeth II Stadium",
    area: "Enfield",
    level: "All levels",
    description: "Fan-owned community football club playing in the National League South. Community programmes include youth development, walking football and disability sessions.",
    contact: "https://www.enfieldtownfc.co.uk",
    sourceUrl: "https://www.enfieldtownfc.co.uk",
    isVenue: false,
  },

  // ===================== HARINGEY =====================
  {
    externalId: "exp-football-haringey-1",
    sport: "Football",
    borough: "Haringey",
    name: "Haringey Borough FC",
    venue: "Coles Park, White Hart Lane",
    area: "Wood Green",
    level: "All levels",
    description: "Community football club based at Coles Park in White Hart Lane area. Competes in the Isthmian League and runs community football programmes.",
    contact: "https://www.haringeyboroughfc.com",
    sourceUrl: "https://www.haringeyboroughfc.com",
    isVenue: false,
  },
  {
    externalId: "exp-running-haringey-1",
    sport: "Running",
    borough: "Haringey",
    name: "Synergy Running Club (Crouch End)",
    venue: "Crouch End area",
    area: "Crouch End",
    level: "All levels",
    description: "Community running club based in Crouch End, Haringey. Regular group runs and sessions for all abilities through local parks and streets.",
    contact: "https://www.crouchendrunning.co.uk",
    sourceUrl: "https://www.crouchendrunning.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-haringey-2",
    sport: "Running",
    borough: "Haringey",
    name: "London Heathside Runners AC",
    venue: "Finsbury Park & North London",
    area: "Finsbury Park",
    level: "All levels",
    description: "Athletic club based in North London offering track, road and cross-country running. Friendly club for all abilities from joggers to elite runners.",
    contact: "https://www.londonheathside.org.uk",
    sourceUrl: "https://www.londonheathside.org.uk",
    isVenue: false,
  },

  // ===================== WALTHAM FOREST =====================
  {
    externalId: "exp-running-walthamforest-1",
    sport: "Running",
    borough: "Waltham Forest",
    name: "Orion Harriers",
    venue: "Chingford area",
    area: "Chingford",
    level: "All levels",
    description: "Athletics club based in Chingford, Waltham Forest. Road running, cross-country and track events through Epping Forest and local routes.",
    contact: "https://www.orionharriers.org.uk",
    sourceUrl: "https://www.orionharriers.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-walthamforest-2",
    sport: "Running",
    borough: "Waltham Forest",
    name: "East London Runners",
    venue: "Wanstead Flats",
    area: "Wanstead",
    level: "All levels",
    description: "Community running club based in Wanstead. Offers sessions for all abilities from beginners to experienced runners. Weekly club runs and social events.",
    contact: "https://www.eastlondonrunners.org.uk",
    sourceUrl: "https://www.eastlondonrunners.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-football-walthamforest-1",
    sport: "Football",
    borough: "Waltham Forest",
    name: "Walthamstow FC",
    venue: "Wadham Lodge Sports Ground",
    area: "Walthamstow",
    level: "All levels",
    description: "Community football club based in Walthamstow. Youth and adult teams competing in local leagues with a focus on community development.",
    contact: "https://www.walthamstowfc.co.uk",
    sourceUrl: "https://www.walthamstowfc.co.uk",
    isVenue: false,
  },

  // ===================== REDBRIDGE =====================
  {
    externalId: "exp-running-redbridge-1",
    sport: "Running",
    borough: "Redbridge",
    name: "Ilford AC",
    venue: "Ilford area & Valentines Park",
    area: "Ilford",
    level: "All levels",
    description: "One of the oldest athletics clubs in East London. Road running, cross-country and track events based in Ilford, Redbridge.",
    contact: "https://www.ilfordathleticclub.co.uk",
    sourceUrl: "https://www.ilfordathleticclub.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-football-redbridge-1",
    sport: "Football",
    borough: "Redbridge",
    name: "Redbridge FC",
    venue: "Oakside Stadium, Barkingside",
    area: "Barkingside",
    level: "All levels",
    description: "Community football club based in Barkingside, Redbridge. Competes in local leagues and runs youth development programmes.",
    contact: "https://www.redbridgefc.co.uk",
    sourceUrl: "https://www.redbridgefc.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-cricket-redbridge-1",
    sport: "Cricket",
    borough: "Redbridge",
    name: "London Cricket Trust (Redbridge)",
    venue: "Valentines Park, Ilford",
    area: "Ilford",
    level: "All levels",
    description: "Community cricket organisation managing cricket activities in Redbridge under the Community Ownership model. Grassroots cricket development in East London.",
    contact: "https://londoncrickettrust.co.uk",
    sourceUrl: "https://londoncrickettrust.co.uk/about-us/",
    isVenue: false,
  },

  // ===================== HOUNSLOW =====================
  {
    externalId: "exp-football-hounslow-1",
    sport: "Football",
    borough: "Hounslow",
    name: "Brentford FC Community Sports Trust",
    venue: "Brentford Community Stadium",
    area: "Brentford",
    level: "All levels",
    description: "Community arm of Brentford FC running football coaching, disability sport, health programmes and community engagement across Hounslow.",
    contact: "https://www.brentfordfccst.com",
    sourceUrl: "https://www.brentfordfccst.com",
    isVenue: false,
  },
  {
    externalId: "exp-running-hounslow-1",
    sport: "Running",
    borough: "Hounslow",
    name: "West 4 Harriers",
    venue: "Chiswick & Hounslow area",
    area: "Chiswick",
    level: "All levels",
    description: "Running club based in Chiswick offering road running, cross-country and social running. Regular weekly sessions for all abilities.",
    contact: "https://www.west4harriers.com",
    sourceUrl: "https://www.west4harriers.com",
    isVenue: false,
  },
  {
    externalId: "exp-cycling-hounslow-1",
    sport: "Cycling",
    borough: "Hounslow",
    name: "Hounslow & District Wheelers",
    venue: "Hounslow area routes",
    area: "Hounslow",
    level: "All levels",
    description: "Cycling club based in Hounslow offering regular group rides of varying distances and speeds. Social and competitive cycling in West London.",
    contact: "https://www.hounslowwheelers.org.uk",
    sourceUrl: "https://www.hounslowwheelers.org.uk",
    isVenue: false,
  },

  // ===================== HAMMERSMITH AND FULHAM =====================
  {
    externalId: "exp-running-hammersmith-1",
    sport: "Running",
    borough: "Hammersmith and Fulham",
    name: "Fulham Running Club",
    venue: "Bishops Park & Thames towpath",
    area: "Fulham",
    level: "All levels",
    description: "Community running club based in Fulham. Regular group runs along the Thames towpath and through local parks for all abilities.",
    contact: "https://www.fulhamrunningclub.org.uk",
    sourceUrl: "https://www.fulhamrunningclub.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-hammersmith-2",
    sport: "Running",
    borough: "Hammersmith and Fulham",
    name: "Thames Valley Harriers",
    venue: "Linford Christie Stadium, White City",
    area: "White City",
    level: "All levels",
    description: "Major athletics club based at Linford Christie Stadium. Track and field, road running and cross-country with elite and community programmes.",
    contact: "https://www.thamesvalleyharriers.com",
    sourceUrl: "https://www.thamesvalleyharriers.com",
    isVenue: false,
  },
  {
    externalId: "exp-football-hammersmith-1",
    sport: "Football",
    borough: "Hammersmith and Fulham",
    name: "Shepherd's Bush 8-a-side Football",
    venue: "Shepherd's Bush area pitches",
    area: "Shepherd's Bush",
    level: "All levels",
    description: "Regular casual 8-a-side football games in Shepherd's Bush. Open to all levels, friendly atmosphere. Organised via Meetup.",
    contact: "https://www.meetup.com/find/gb--twickenham/5-a-side-football/",
    sourceUrl: "https://www.meetup.com/find/gb--twickenham/5-a-side-football/",
    isVenue: false,
  },

  // ===================== MERTON =====================
  {
    externalId: "exp-running-merton-1",
    sport: "Running",
    borough: "Merton",
    name: "Hercules Wimbledon AC",
    venue: "Wimbledon Park Athletics Track",
    area: "Wimbledon",
    level: "All levels",
    description: "Athletics club based in Wimbledon. Track and field, road running and cross-country. Programmes for juniors and adults.",
    contact: "https://www.herculeswimbledonac.org.uk",
    sourceUrl: "https://www.herculeswimbledonac.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-merton-2",
    sport: "Running",
    borough: "Merton",
    name: "Wimbledon Windmilers",
    venue: "Wimbledon Common",
    area: "Wimbledon",
    level: "All levels",
    description: "Social running club based on Wimbledon Common. Weekly runs for all abilities with a strong social element.",
    contact: "https://www.windmilers.org.uk",
    sourceUrl: "https://www.windmilers.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-tennis-merton-1",
    sport: "Tennis",
    borough: "Merton",
    name: "Wimbledon Park Tennis",
    venue: "Wimbledon Park",
    area: "Wimbledon",
    level: "All levels",
    description: "Public tennis courts in Wimbledon Park offering pay-and-play tennis, coaching and social sessions in the heart of Merton.",
    contact: "https://www.better.org.uk/leisure-centre/london/merton",
    sourceUrl: "https://www.better.org.uk/leisure-centre/london/merton",
    isVenue: true,
  },

  // ===================== CROYDON =====================
  {
    externalId: "exp-running-croydon-1",
    sport: "Running",
    borough: "Croydon",
    name: "Croydon Harriers",
    venue: "Croydon Arena, South Norwood",
    area: "South Norwood",
    level: "All levels",
    description: "One of the oldest athletics clubs in the UK, founded in 1921. Track and field, road running and cross-country at Croydon Arena.",
    contact: "https://www.croydonharriers.com",
    sourceUrl: "https://www.croydonharriers.com",
    isVenue: false,
  },
  {
    externalId: "exp-running-croydon-2",
    sport: "Running",
    borough: "Croydon",
    name: "Striders of Croydon",
    venue: "Croydon area",
    area: "Croydon",
    level: "All levels",
    description: "Friendly running club based in Croydon. Road running and cross-country for all abilities with regular weekly sessions.",
    contact: "https://www.stridersofcroydon.org.uk",
    sourceUrl: "https://www.stridersofcroydon.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-football-croydon-1",
    sport: "Football",
    borough: "Croydon",
    name: "5-a-side Football South London (Croydon)",
    venue: "Various South London pitches",
    area: "Croydon",
    level: "All levels",
    description: "Popular weekly friendly 5-a-side football games in South London covering Croydon, Morden and Sutton. £10 per session, all welcome.",
    contact: "https://www.meetup.com/5-a-side-footy-in-carshalton-and-sutton/",
    sourceUrl: "https://www.meetup.com/5-a-side-footy-in-carshalton-and-sutton/",
    isVenue: false,
  },

  // ===================== BROMLEY =====================
  {
    externalId: "exp-running-bromley-1",
    sport: "Running",
    borough: "Bromley",
    name: "Blackheath and Bromley Harriers AC",
    venue: "Norman Park Athletics Track, Hayes",
    area: "Hayes",
    level: "All levels",
    description: "Major athletics club based at Norman Park in Hayes, Bromley. Road, track, cross-country, field events for all ages and abilities.",
    contact: "https://www.bandbhac.org.uk",
    sourceUrl: "https://www.bandbhac.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-bromley-2",
    sport: "Running",
    borough: "Bromley",
    name: "Beckenham Running Club",
    venue: "Beckenham Place Park",
    area: "Beckenham",
    level: "All levels",
    description: "Community running club based in Beckenham, Bromley. Regular group runs and social events for runners of all levels.",
    contact: "https://www.beckenhamrunning.co.uk",
    sourceUrl: "https://www.beckenhamrunning.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-tennis-bromley-1",
    sport: "Tennis",
    borough: "Bromley",
    name: "Bromley Lawn Tennis & Squash Club",
    venue: "Bromley LTSC",
    area: "Bromley",
    level: "All levels",
    description: "Premier tennis and squash club with 14 courts indoor and outdoor, 3 squash courts and pickleball. Coaching, social tennis and competitive play.",
    contact: "https://www.bromleyltsc.co.uk",
    sourceUrl: "https://www.bromleyltsc.co.uk",
    isVenue: true,
  },
  {
    externalId: "exp-cycling-bromley-1",
    sport: "Cycling",
    borough: "Bromley",
    name: "Bromley Cycling Club",
    venue: "Various routes from Bromley",
    area: "Bromley",
    level: "All levels",
    description: "Community cycling club listed by Bromley Council. Regular rides catering for every kind of cyclist, from beginners to racers.",
    contact: "https://www.bromley.gov.uk/cycling/local-cycling-clubs-organisations",
    sourceUrl: "https://www.bromley.gov.uk/cycling/local-cycling-clubs-organisations",
    isVenue: false,
  },

  // ===================== BARKING AND DAGENHAM =====================
  {
    externalId: "exp-running-barking-1",
    sport: "Running",
    borough: "Barking and Dagenham",
    name: "Barking Road Runners",
    venue: "Barking area",
    area: "Barking",
    level: "All levels",
    description: "Community running club based in Barking. Road running and cross-country for all abilities with regular training sessions.",
    contact: "https://www.barkingroadrunners.org.uk",
    sourceUrl: "https://www.barkingroadrunners.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-barking-2",
    sport: "Running",
    borough: "Barking and Dagenham",
    name: "Dagenham 88 Runners",
    venue: "Dagenham area",
    area: "Dagenham",
    level: "All levels",
    description: "Established running club based in Dagenham. Regular training runs, road races and cross-country for all abilities.",
    contact: "https://www.dagenham88runners.com",
    sourceUrl: "https://www.dagenham88runners.com",
    isVenue: false,
  },
  {
    externalId: "exp-football-barking-1",
    sport: "Football",
    borough: "Barking and Dagenham",
    name: "Barking FC",
    venue: "Mayesbrook Park",
    area: "Barking",
    level: "All levels",
    description: "Historic community football club based in Barking. One of the oldest clubs in East London with senior and youth teams.",
    contact: "https://www.barkingfc.co.uk",
    sourceUrl: "https://www.barkingfc.co.uk",
    isVenue: false,
  },

  // ===================== SUTTON =====================
  {
    externalId: "exp-running-sutton-1",
    sport: "Running",
    borough: "Sutton",
    name: "Sutton & District AC",
    venue: "Carshalton area",
    area: "Carshalton",
    level: "All levels",
    description: "Athletics club based in Carshalton, Sutton. Track and field, road running and cross-country for juniors and seniors.",
    contact: "https://www.suttondistrictac.co.uk",
    sourceUrl: "https://www.suttondistrictac.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-sutton-2",
    sport: "Running",
    borough: "Sutton",
    name: "Sutton Runners",
    venue: "Carshalton area parks",
    area: "Carshalton",
    level: "All levels",
    description: "Friendly community running club based in Carshalton, Sutton. Regular group runs and social events for all abilities.",
    contact: "https://www.suttonrunners.org",
    sourceUrl: "https://www.suttonrunners.org",
    isVenue: false,
  },
  {
    externalId: "exp-football-sutton-1",
    sport: "Football",
    borough: "Sutton",
    name: "5-a-side Football South London (Sutton)",
    venue: "Carshalton indoor pitches",
    area: "Carshalton",
    level: "All levels",
    description: "Weekly friendly 5-a-side football in Carshalton/Sutton. £10 per session, managed via Meetup. Regular and welcoming community.",
    contact: "https://www.meetup.com/5-a-side-footy-in-carshalton-and-sutton/",
    sourceUrl: "https://www.meetup.com/5-a-side-footy-in-carshalton-and-sutton/",
    isVenue: false,
  },

  // ===================== HARROW =====================
  {
    externalId: "exp-running-harrow-1",
    sport: "Running",
    borough: "Harrow",
    name: "Harrow AC",
    venue: "Harrow Weald area",
    area: "Harrow Weald",
    level: "All levels",
    description: "Athletics club based in Harrow Weald. Track and field, road running and cross-country for juniors and seniors.",
    contact: "https://www.harrowac.co.uk",
    sourceUrl: "https://www.harrowac.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-harrow-2",
    sport: "Running",
    borough: "Harrow",
    name: "Metros Running Club",
    venue: "Pinner area",
    area: "Pinner",
    level: "All levels",
    description: "Community running club based in Pinner, Harrow. Regular training sessions and social runs for all abilities.",
    contact: "https://www.metros.org.uk",
    sourceUrl: "https://www.metros.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-football-harrow-1",
    sport: "Football",
    borough: "Harrow",
    name: "Harrow Borough FC",
    venue: "Earlsmead Stadium",
    area: "Harrow",
    level: "All levels",
    description: "Community football club based at Earlsmead Stadium. Competes in the Isthmian League with community youth and adult programmes.",
    contact: "https://www.harrowboro.com",
    sourceUrl: "https://www.harrowboro.com",
    isVenue: false,
  },

  // ===================== HILLINGDON =====================
  {
    externalId: "exp-running-hillingdon-1",
    sport: "Running",
    borough: "Hillingdon",
    name: "Hillingdon AC",
    venue: "Hillingdon Athletics Stadium, Ruislip",
    area: "Ruislip",
    level: "All levels",
    description: "Athletics club based at Hillingdon Athletics Stadium in Ruislip. Track and field, road running and cross-country for all ages.",
    contact: "https://www.hillingdonac.co.uk",
    sourceUrl: "https://www.hillingdonac.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-hillingdon-2",
    sport: "Running",
    borough: "Hillingdon",
    name: "Hayes & Harlington Road Runners",
    venue: "Hayes area",
    area: "Hayes",
    level: "All levels",
    description: "Community running club based in Hayes, Hillingdon. Regular road running and cross-country sessions for all abilities.",
    contact: "https://www.hhroadrunners.com",
    sourceUrl: "https://www.hhroadrunners.com",
    isVenue: false,
  },
  {
    externalId: "exp-football-hillingdon-1",
    sport: "Football",
    borough: "Hillingdon",
    name: "Uxbridge FC",
    venue: "Honeycroft, Uxbridge",
    area: "Uxbridge",
    level: "All levels",
    description: "Community football club based in Uxbridge, Hillingdon. Long-standing non-league club with senior and youth teams.",
    contact: "https://www.uxbridgefc.co.uk",
    sourceUrl: "https://www.uxbridgefc.co.uk",
    isVenue: false,
  },

  // ===================== HAVERING =====================
  {
    externalId: "exp-running-havering-1",
    sport: "Running",
    borough: "Havering",
    name: "Havering '90 Joggers",
    venue: "Hornchurch area",
    area: "Hornchurch",
    level: "All levels",
    description: "Friendly jogging and running club based in Hornchurch, Havering. Regular group runs for all abilities from beginners to experienced runners.",
    contact: "https://www.h90j.org.uk",
    sourceUrl: "https://www.h90j.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-havering-2",
    sport: "Running",
    borough: "Havering",
    name: "Havering AC",
    venue: "Upminster area",
    area: "Upminster",
    level: "All levels",
    description: "Athletics club based in Upminster, Havering. Track and field, road running and cross-country for juniors and seniors.",
    contact: "https://www.havering-mayesbrook.org",
    sourceUrl: "https://www.havering-mayesbrook.org",
    isVenue: false,
  },
  {
    externalId: "exp-football-havering-1",
    sport: "Football",
    borough: "Havering",
    name: "Hornchurch FC",
    venue: "Bridge Avenue, Upminster",
    area: "Upminster",
    level: "All levels",
    description: "Community football club based in Upminster. Competes in the Isthmian League with community programmes and youth development.",
    contact: "https://www.hornchurchfc.com",
    sourceUrl: "https://www.hornchurchfc.com",
    isVenue: false,
  },

  // ===================== RICHMOND UPON THAMES =====================
  {
    externalId: "exp-running-richmond-1",
    sport: "Running",
    borough: "Richmond upon Thames",
    name: "Ranelagh Harriers",
    venue: "Richmond Park & Petersham",
    area: "Richmond",
    level: "All levels",
    description: "Historic running club based near Richmond Park. Cross-country, road and track running with a strong social element. One of the oldest clubs in London.",
    contact: "https://www.ranelagh-harriers.com",
    sourceUrl: "https://www.ranelagh-harriers.com",
    isVenue: false,
  },
  {
    externalId: "exp-running-richmond-2",
    sport: "Running",
    borough: "Richmond upon Thames",
    name: "Barnes Runners",
    venue: "Barnes area & Thames towpath",
    area: "Barnes",
    level: "All levels",
    description: "Community running club based in Barnes. Regular group runs along the Thames towpath and through local parks for all abilities.",
    contact: "https://www.barnesrunners.org",
    sourceUrl: "https://www.barnesrunners.org",
    isVenue: false,
  },
  {
    externalId: "exp-rugby-richmond-1",
    sport: "Rugby",
    borough: "Richmond upon Thames",
    name: "Richmond Rugby Club",
    venue: "Richmond Athletic Ground",
    area: "Richmond",
    level: "All levels",
    description: "Historic rugby club based at the Richmond Athletic Ground. Senior men's and women's teams plus youth and mini rugby programmes.",
    contact: "https://www.richmondfc.co.uk",
    sourceUrl: "https://www.richmondfc.co.uk",
    isVenue: false,
  },

  // ===================== KINGSTON UPON THAMES =====================
  {
    externalId: "exp-running-kingston-1",
    sport: "Running",
    borough: "Kingston upon Thames",
    name: "Kingston AC and Poly Harriers",
    venue: "Kingston & Surbiton area",
    area: "Kingston",
    level: "All levels",
    description: "Athletics club based in Kingston upon Thames. Road running, cross-country and track for all ages and abilities.",
    contact: "https://www.kingstonandpoly.org",
    sourceUrl: "https://www.kingstonandpoly.org",
    isVenue: false,
  },
  {
    externalId: "exp-running-kingston-2",
    sport: "Running",
    borough: "Kingston upon Thames",
    name: "The Stragglers Running Club",
    venue: "Ham & Kingston area",
    area: "Ham",
    level: "All levels",
    description: "Friendly running club based in Ham, Kingston. Road running, cross-country and social running for all abilities.",
    contact: "https://www.stragglers.org",
    sourceUrl: "https://www.stragglers.org",
    isVenue: false,
  },
  {
    externalId: "exp-padel-kingston-1",
    sport: "Padel",
    borough: "Kingston upon Thames",
    name: "Playtime Padel Club Kingston",
    venue: "Kingston area",
    area: "Kingston",
    level: "All levels",
    description: "Local padel club with courts in Kingston. Pay and play, social sessions, coaching and competitive match play available.",
    contact: "https://www.playtimepadelclub.com",
    sourceUrl: "https://www.playtimepadelclub.com",
    isVenue: true,
  },

  // ===================== BEXLEY =====================
  {
    externalId: "exp-running-bexley-1",
    sport: "Running",
    borough: "Bexley",
    name: "Bexley AC",
    venue: "Erith area",
    area: "Erith",
    level: "All levels",
    description: "Athletics club based in Erith, Bexley. Track and field, road running and cross-country for all ages and abilities.",
    contact: "https://www.bexleyac.org.uk",
    sourceUrl: "https://www.bexleyac.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-bexley-2",
    sport: "Running",
    borough: "Bexley",
    name: "Plumstead Runners",
    venue: "Welling area",
    area: "Welling",
    level: "All levels",
    description: "Community running club based in Welling, Bexley. Regular group runs and cross-country sessions for all abilities.",
    contact: "https://www.plumsteadrunners.co.uk",
    sourceUrl: "https://www.plumsteadrunners.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-tennis-bexley-1",
    sport: "Tennis",
    borough: "Bexley",
    name: "Bexley Lawn Tennis, Squash and Racketball Club",
    venue: "Bexley LTSRC",
    area: "Bexley",
    level: "All levels",
    description: "Tennis and squash club in Bexley offering coaching, social play and competitive matches. Part of the North Kent LTA.",
    contact: "https://northkentlta.org.uk/clubs",
    sourceUrl: "https://northkentlta.org.uk/clubs",
    isVenue: true,
  },

  // ===================== CITY OF LONDON =====================
  {
    externalId: "exp-running-city-1",
    sport: "Running",
    borough: "City of London",
    name: "Serpentine Running Club",
    venue: "Hyde Park & Central London",
    area: "Central London",
    level: "All levels",
    description: "One of London's largest and most prestigious running clubs. Regular sessions in Hyde Park and central London. Road, track and cross-country for all abilities.",
    contact: "https://www.serpentine.org.uk",
    sourceUrl: "https://www.serpentine.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-running-city-2",
    sport: "Running",
    borough: "City of London",
    name: "London Frontrunners",
    venue: "Central London parks",
    area: "Central London",
    level: "All levels",
    description: "Inclusive LGBTQ+ running club based in central London. Weekly runs from various central London locations for all abilities.",
    contact: "https://www.londonfrontrunners.org",
    sourceUrl: "https://www.londonfrontrunners.org",
    isVenue: false,
  },
  {
    externalId: "exp-cycling-city-1",
    sport: "Cycling",
    borough: "City of London",
    name: "London Cycling Campaign - City",
    venue: "City of London routes",
    area: "City of London",
    level: "All levels",
    description: "Cycling advocacy and community rides through the City of London. Group rides and events promoting cycling in central London.",
    contact: "https://www.lcc.org.uk",
    sourceUrl: "https://www.lcc.org.uk",
    isVenue: false,
  },

  // ===================== EXTRA: LAMBETH (thin borough) =====================
  {
    externalId: "exp-running-lambeth-1",
    sport: "Running",
    borough: "Lambeth",
    name: "Herne Hill Harriers",
    venue: "Tooting Bec Athletics Track",
    area: "Herne Hill",
    level: "All levels",
    description: "Historic athletics club based in the Herne Hill area. Track, road and cross-country running for juniors and seniors. One of London's oldest clubs.",
    contact: "https://www.hernehillharriers.org",
    sourceUrl: "https://www.hernehillharriers.org",
    isVenue: false,
  },
  {
    externalId: "exp-running-lambeth-2",
    sport: "Running",
    borough: "Lambeth",
    name: "Clapham Pioneers",
    venue: "Clapham Common",
    area: "Clapham",
    level: "All levels",
    description: "Running club based on Clapham Common offering group sessions for all abilities. Regular weekly training and social events.",
    contact: "https://www.claphampioneers.co.uk",
    sourceUrl: "https://www.claphampioneers.co.uk",
    isVenue: false,
  },
  {
    externalId: "exp-cycling-lambeth-1",
    sport: "Cycling",
    borough: "Lambeth",
    name: "Herne Hill Velodrome",
    venue: "Herne Hill Velodrome, Burbage Road",
    area: "Herne Hill",
    level: "All levels",
    description: "Historic velodrome (1948 Olympics venue) offering track cycling sessions, coaching and community rides. Open to all from beginners to experienced riders.",
    contact: "https://www.hernehillvelodrome.com",
    sourceUrl: "https://www.hernehillvelodrome.com",
    isVenue: true,
  },

  // ===================== EXTRA: WESTMINSTER (thin borough) =====================
  {
    externalId: "exp-running-westminster-1",
    sport: "Running",
    borough: "Westminster",
    name: "We Run - North London (Marylebone)",
    venue: "Regent's Park, Marylebone",
    area: "Marylebone",
    level: "All levels",
    description: "Community running group meeting in Regent's Park, Marylebone. Free weekly runs for all abilities with a social vibe.",
    contact: "https://www.we-run.co.uk/running-club-north-london/",
    sourceUrl: "https://www.we-run.co.uk/running-club-north-london/",
    isVenue: false,
  },
  {
    externalId: "exp-yoga-westminster-1",
    sport: "Yoga",
    borough: "Westminster",
    name: "Yoga in the Park - Hyde Park",
    venue: "Hyde Park",
    area: "Hyde Park",
    level: "All levels",
    description: "Free outdoor yoga sessions in Hyde Park during summer months. Community-organised classes for all levels in central London.",
    contact: "https://www.royalparks.org.uk/parks/hyde-park",
    sourceUrl: "https://www.royalparks.org.uk/parks/hyde-park",
    isVenue: false,
  },

  // ===================== EXTRA: KENSINGTON AND CHELSEA (thin borough) =====================
  {
    externalId: "exp-running-kensington-1",
    sport: "Running",
    borough: "Kensington and Chelsea",
    name: "Serpentine RC (Kensington Gardens)",
    venue: "Kensington Gardens & Hyde Park",
    area: "Kensington",
    level: "All levels",
    description: "Regular Serpentine RC sessions through Kensington Gardens. Track sessions, tempo runs and social runs for members of all abilities.",
    contact: "https://www.serpentine.org.uk",
    sourceUrl: "https://www.serpentine.org.uk",
    isVenue: false,
  },
  {
    externalId: "exp-swimming-kensington-1",
    sport: "Swimming",
    borough: "Kensington and Chelsea",
    name: "Serpentine Swimming Club",
    venue: "The Serpentine, Hyde Park",
    area: "Kensington",
    level: "All levels",
    description: "Historic open water swimming club at the Serpentine in Hyde Park. Year-round outdoor swimming including the famous Christmas Day race.",
    contact: "https://www.serpentineswimmingclub.com",
    sourceUrl: "https://www.serpentineswimmingclub.com",
    isVenue: false,
  },
];

async function main() {
  console.log(`Seeding ${groups.length} expansion groups...`);

  let created = 0;
  let updated = 0;

  for (const group of groups) {
    try {
      const result = await prisma.group.upsert({
        where: { externalId: group.externalId },
        update: {
          sport: group.sport,
          borough: group.borough,
          name: group.name,
          venue: group.venue,
          area: group.area,
          level: group.level,
          description: group.description,
          contact: group.contact,
          sourceUrl: group.sourceUrl,
          isVenue: group.isVenue,
          status: "APPROVED",
          sourceType: "MANUAL_ENTRY",
        },
        create: {
          externalId: group.externalId,
          sport: group.sport,
          borough: group.borough,
          name: group.name,
          venue: group.venue,
          area: group.area,
          level: group.level,
          description: group.description,
          contact: group.contact,
          sourceUrl: group.sourceUrl,
          isVenue: group.isVenue,
          status: "APPROVED",
          sourceType: "MANUAL_ENTRY",
        },
      });
      console.log(`✓ ${group.borough} | ${group.sport} | ${group.name}`);
      created++;
    } catch (err: any) {
      console.error(`✗ ${group.name}: ${err.message}`);
    }
  }

  console.log(`\nDone! Processed ${created} groups.`);
}

main()
  .catch((e) => {
    console.error("Error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
